#!/bin/sh

here=`dirname $0`
source settings

debug=


info() {
	if [ "x$debug" = "x" ]; then
		return
	fi
	echo $@
}

help() {
	echo "Usage: $0 [-v] [help|shuffle|add [word]...]"
	echo "By default shows word and its translation from dictionary file every time script"
	echo "is called. It will increment pointer after showing word. When all words"
	echo "has been shown the dictionary file will be shuffled."
	echo "If you want more verbose output add '-v' before other parameters."
	echo
	echo "Available commands:"
	echo "  help     " "Shows this helpful description"
	echo "  add      " "Adds a word(s) to the dictionary and retrieves its translation(s)"
	echo "           " "Type add without parameters more informations"
	echo "  shuffle  " "Shuffles entire dictionary file"
	echo "  retrieve " "Get all missing translations from internet"
	exit 0
}

shuffle() {
	info "Shuffling dictionary file."
	info "Previous version of dictionary file is stored under $dictionary.prev."
	cp $dictionary $dictionary.prev
	sort -R $dictionary.prev -o $dictionary
	echo 1 > $pointer
}

show_and_increment_pointer() {
	if [ -e $pointer ]; then
		nr=`cat $pointer`
		if [ -z "$nr" ]; then
			info "No data in pointer file, correcting."
			nr=1
		elif [ $((nr)) -le 0 ]; then
			info "Something wrong with pointer file, correcting."
			# exit 1
			nr=1
		fi
	else
		info "Creating pointer file."
		# echo 1 > $pointer
		nr=1
	fi
	
	info "Your word (#$nr) is:"
	word=`head -$nr $dictionary | tail -1`
	wordfile="$data/$word.html"

	if [ ! -e "$wordfile" ]; then
		echo "File with translation missing!"
		echo "To fix it type: $0 retrieve"
		exit 1
	fi

	# Show translation on screen
	./dump "$wordfile"

	total=`wc -l $dictionary | cut -d' ' -f1`
	if [ $((nr)) -ge $((total)) ]; then
		info "All words has been shown."
		shuffle
		info "Reseting pointer."
		echo 1 > $pointer
	else
		info "Incrementing and saving pointer."
		echo $((nr+1)) > $pointer
	fi
}

retrieve() {
	cat $dictionary | while read line; do
		wget -nc "http://www.diki.pl/slownik-angielskiego/?q=$line" -O "$data/$line.html" --quiet \
		|| "Cannot retrieve '$line'"
	done
	# ls $data | while read line; do
	# 	./dump "$line" > 
	# done
}


while true; do # Or should it be [ $# -gt 0 ] ?
	case $1 in
		"-v")
			debug=true
			shift
			continue
			;;
		"--help"|"help")
			help
			;;
		"add")
			shift
			./add "$@"
			;;
		"shuffle")
			shuffle
			;;
		"retrieve")
			retrieve
			;;
		*)
			show_and_increment_pointer
	esac
	break
done
